<?php
use Drupal\Core\Form\FormStateInterface;

function ari_extras_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {



    if($form['#id'] === "views-exposed-form-blog-page-1") {

        // Hide sort by options if theres only one variant.
        $sort_by_options = count($form['sort_by']['#options']);
        if($sort_by_options < 2) {
            $form['sort_by']['#states']['visible'] = [
                'select[name="sort_order"]' => array('value' => 'FALSE')
            ];
        }

        // Update form when select value is changed.
        $form['sort_order']['#attributes'] = array('onchange' => 'this.form.submit();');

        // Hide submit button
        unset($form['actions']['submit']);
    }
  }