_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  ari_extras: 0
  ari_formatters: 0
  ari_reference_color: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  color_field: 0
  config: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  help: 0
  history: 0
  image: 0
  link: 0
  material_icons: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phone_number: 0
  search: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  gin: 0
  stable9: 0
  ari: 0
profile: standard
