_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 4621e32a-4eba-4f4e-b079-164c2e8cea8e
name: 'ARI 🇦🇺 AUSTRALIA'
mail: ari_lybaert@outlook.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
